### ISSUE TITLE
Embeds dont work using channel.send

### ISSUE THREAD

**Issue by 2vw** [EnokiUN/voltage#97]
### Summary

channel.send(embed=embed) doesnt work

### Reproduction Steps

try and send embed to channel by id
embed=embed
```py
Task exception was never retrieved
future: <Task finished name='Task-1943' coro=<levelstuff() done, defined at c:\Users\willi\Desktop\mecharemakecode\main.py:135> exception=TypeError('Object of type Asset is not JSON serializable')>
Traceback (most recent call last):
  File "c:\Users\willi\Desktop\mecharemakecode\main.py", line 147, in levelstuff
    await msg.edit(embed=embed)
  File "C:\Users\willi\AppData\Local\Programs\Python\Python312\Lib\site-packages\voltage\message.py", line 227, in edit
    await self.cache.http.edit_message(self.channel.id, self.id, content=content, embeds=embeds)
  File "C:\Users\willi\AppData\Local\Programs\Python\Python312\Lib\site-packages\voltage\internals\http.py", line 524, in edit_message
    return await self.request("PATCH", f"channels/{channel_id}/messages/{message_id}", json=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\willi\AppData\Local\Programs\Python\Python312\Lib\site-packages\voltage\internals\http.py", line 87, in request
    async with self.client.request(method, self.api_url + url, headers=header, **kwargs) as request:
  File "C:\Users\willi\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\willi\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\client.py", line 434, in _request
    data = payload.JsonPayload(json, dumps=self._json_serialize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\willi\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\payload.py", line 396, in __init__
    dumps(value).encode(encoding),
    ^^^^^^^^^^^^
  File "C:\Users\willi\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\willi\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\willi\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\willi\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Asset is not JSON serializable
```

### Minimal Reproducible Code

```python
channel = client.get_channel(config['LEVEL_CHANNEL'])
      embed = voltage.SendableEmbed(
        title = f"{message.author.name} has leveled up!",
        description = f"**{get_user(message.author)['levels']['level']}**",
        color = "#44ff44",
        icon_url = message.author.avatar,
        media = "https://ibb.co/mcTxwnf"
      )
      await channel.send(embed=embed)
```

### Expected Results

send an embed

### Actual Results

it errored out and nothing happened

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by EnokiUN** [comment]
Try using `message.author.avatar.url` instead of `message.author.avatar`
